### ISSUE TITLE
ssl.c:1059: The handshake operation timed out

### ISSUE THREAD

**Issue by kc2cbd** [gpodder/gpodder#732] opened 2020-01-17 02:23 UTC
Can't seem to update my podcasts.

Log shows the following

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\gPodder\lib\python3.7\site-packages\gpodder\download.py", line 813, in run
    self.tempname, reporthook=self.status_updated)
  File "C:\Program Files (x86)\gPodder\lib\python3.7\site-packages\gpodder\download.py", line 315, in retrieve_resume
    fp = self.open(url, data)
  File "request.py", line 1762, in open
  File "request.py", line 1756, in open
  File "request.py", line 1965, in open_https
  File "request.py", line 1914, in _open_generic_http
  File "client.py", line 1244, in request
  File "client.py", line 1290, in _send_request
  File "client.py", line 1239, in endheaders
  File "client.py", line 1026, in _send_output
  File "client.py", line 966, in send
  File "client.py", line 1414, in connect
  File "ssl.py", line 423, in wrap_socket
  File "ssl.py", line 870, in _create
  File "ssl.py", line 1139, in do_handshake
OSError: [Errno socket error] _ssl.c:1059: The handshake operation timed out

```

This is on Windows 10 Version 1909 OS Build 18363.592

Thanks
Dale

**Comment by auouymous** [comment] 2020-01-17 20:35
Does every podcast generate that error when updating individually? Do you have podcasts from different sites, and do they generate the same error?

**Comment by kc2cbd** [comment] 2020-01-17 20:41
Every podcast from blubrry at the present that I can see.

**Comment by auouymous** [comment] 2020-01-17 22:10
Can you post a feed URL that doesn't work?

**Comment by kc2cbd** [comment] 2020-01-17 22:54
Sure, this is one of them.

https://feeds.blubrry.com/feeds/arrlontheair.xml

**Comment by auouymous** [comment] 2020-01-17 23:46
I was able to install and download an episode from that podcast in gpodder.

Does that URL work when you open it in a browser on the same computer? Are you using gpodder 3.10.11?

**Comment by kc2cbd** [comment] 2020-01-18 06:17
I can view that page and download the mp3's in a browser.
But for some reason recently that new one and other ones on blubrry fail with the previous time out.
I am running 3.10.11

Thanks

**Comment by kc2cbd** [comment] 2020-01-19 01:33
Here is more from the logs

```
2020-01-18 19:18:54,703 [gpodder.util] WARNING: html5lib not found, falling back to HTMLParser
2020-01-18 19:19:00,421 [gpodder.sync] WARNING: Could not find gpod
2020-01-18 19:19:00,421 [gpodder.sync] WARNING: Could not find eyed3.mp3
2020-01-18 19:19:10,149 [gpodder.gtkui.desktopfile] WARNING: Parse HKEY error: HKEY_CLASSES_ROOT\Winamp.File\shell\Play\command ([WinError 2] The system cannot find the file specified)
2020-01-18 19:19:10,150 [gpodder.gtkui.desktopfile] WARNING: Parse HKEY error: HKEY_CLASSES_ROOT\Applications\foobar2000.exe\shell\open\command ([WinError 2] The system cannot find the file specified)
2020-01-18 19:19:10,150 [gpodder.gtkui.desktopfile] WARNING: Parse HKEY error: HKEY_CLASSES_ROOT\WMP11.AssocFile.MP3\shell\open\command ([WinError 2] The system cannot find the file specified)
2020-01-18 19:19:10,150 [gpodder.gtkui.desktopfile] WARNING: Parse HKEY error: HKEY_CLASSES_ROOT\QuickTime.mp3\shell\open\command ([WinError 2] The system cannot find the file specified)
2020-01-18 19:20:25,291 [gpodder.download] ERROR: _ssl.c:1059: The handshake operation timed out while downloading "Trailer Episode ARRL's On The Air Podcast": None
Traceback (most recent call last):
  File "request.py", line 1756, in open
  File "request.py", line 1965, in open_https
  File "request.py", line 1914, in _open_generic_http
  File "client.py", line 1244, in request
  File "client.py", line 1290, in _send_request
  File "client.py", line 1239, in endheaders
  File "client.py", line 1026, in _send_output
  File "client.py", line 966, in send
  File "client.py", line 1414, in connect
  File "ssl.py", line 423, in wrap_socket
  File "ssl.py", line 870, in _create
  File "ssl.py", line 1139, in do_handshake
socket.timeout: _ssl.c:1059: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\gPodder\lib\python3.7\site-packages\gpodder\download.py", line 813, in run
    self.tempname, reporthook=self.status_updated)
  File "C:\Program Files (x86)\gPodder\lib\python3.7\site-packages\gpodder\download.py", line 315, in retrieve_resume
    fp = self.open(url, data)
  File "request.py", line 1762, in open
  File "request.py", line 1756, in open
  File "request.py", line 1965, in open_https
  File "request.py", line 1914, in _open_generic_http
  File "client.py", line 1244, in request
  File "client.py", line 1290, in _send_request
  File "client.py", line 1239, in endheaders
  File "client.py", line 1026, in _send_output
  File "client.py", line 966, in send
  File "client.py", line 1414, in connect
  File "ssl.py", line 423, in wrap_socket
  File "ssl.py", line 870, in _create
  File "ssl.py", line 1139, in do_handshake
OSError: [Errno socket error] _ssl.c:1059: The handshake operation timed out
2020-01-18 19:20:48,135 [gpodder.my] WARNING: Flush requested, but sync disabled.
```

I have no idea what eyed3.mp3 is but it is showing up.
I don't know if this will help or not.

Thanks
Dale

**Comment by auouymous** [comment] 2020-01-19 05:48
The gpod and eyed3 warnings are fine.

Does gpodder install python on windows or did you install it separately? You could try reinstalling python or gpodder and it might fix the ssl issue.

If python is included with gpodder, you could try installing the git version which might include an updated python. https://ci.appveyor.com/project/elelay/gpodder/builds/30095650/artifacts

If none of that works, read https://gpodder.github.io/docs/windows.html#debugging-gpodder-on-windows and post the debug log.

**Comment by kc2cbd** [comment] 2020-01-19 20:33
Made sure there was only the python that gpodder installs.

Re-installed gpodder after a reboot.

The link you give for debug is just the another way to retrieve the log that is already saved in plain text under logs folder.

Still get this

```
2020-01-19 14:26:53,038 [gpodder.util] WARNING: html5lib not found, falling back to HTMLParser
2020-01-19 14:26:53,362 [gpodder.sync] WARNING: Could not find gpod
2020-01-19 14:26:53,363 [gpodder.sync] WARNING: Could not find eyed3.mp3
2020-01-19 14:26:56,017 [gpodder.gtkui.desktopfile] WARNING: Parse HKEY error: HKEY_CLASSES_ROOT\Winamp.File\shell\Play\command ([WinError 2] The system cannot find the file specified)
2020-01-19 14:26:56,018 [gpodder.gtkui.desktopfile] WARNING: Parse HKEY error: HKEY_CLASSES_ROOT\Applications\foobar2000.exe\shell\open\command ([WinError 2] The system cannot find the file specified)
2020-01-19 14:26:56,018 [gpodder.gtkui.desktopfile] WARNING: Parse HKEY error: HKEY_CLASSES_ROOT\WMP11.AssocFile.MP3\shell\open\command ([WinError 2] The system cannot find the file specified)
2020-01-19 14:26:56,018 [gpodder.gtkui.desktopfile] WARNING: Parse HKEY error: HKEY_CLASSES_ROOT\QuickTime.mp3\shell\open\command ([WinError 2] The system cannot find the file specified)
2020-01-19 14:28:06,050 [gpodder.download] ERROR: _ssl.c:1059: The handshake operation timed out while downloading "Trailer Episode ARRL's On The Air Podcast": None
Traceback (most recent call last):
  File "request.py", line 1756, in open
  File "request.py", line 1965, in open_https
  File "request.py", line 1914, in _open_generic_http
  File "client.py", line 1244, in request
  File "client.py", line 1290, in _send_request
  File "client.py", line 1239, in endheaders
  File "client.py", line 1026, in _send_output
  File "client.py", line 966, in send
  File "client.py", line 1414, in connect
  File "ssl.py", line 423, in wrap_socket
  File "ssl.py", line 870, in _create
  File "ssl.py", line 1139, in do_handshake
socket.timeout: _ssl.c:1059: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\gPodder\lib\python3.7\site-packages\gpodder\download.py", line 813, in run
    self.tempname, reporthook=self.status_updated)
  File "C:\Program Files (x86)\gPodder\lib\python3.7\site-packages\gpodder\download.py", line 315, in retrieve_resume
    fp = self.open(url, data)
  File "request.py", line 1762, in open
  File "request.py", line 1756, in open
  File "request.py", line 1965, in open_https
  File "request.py", line 1914, in _open_generic_http
  File "client.py", line 1244, in request
  File "client.py", line 1290, in _send_request
  File "client.py", line 1239, in endheaders
  File "client.py", line 1026, in _send_output
  File "client.py", line 966, in send
  File "client.py", line 1414, in connect
  File "ssl.py", line 423, in wrap_socket
  File "ssl.py", line 870, in _create
  File "ssl.py", line 1139, in do_handshake
OSError: [Errno socket error] _ssl.c:1059: The handshake operation timed out
```

I believe it has something to do with the missing html5lib.
html5 is going to be the standard soon.

Thanks
Dale

**Comment by elelay** [comment] 2020-01-25 16:16
I can't reproduce the behaviour on a windows 10 VM with the build referenced by auouymous or the newer gPodder 3.10.12.
Tried with https://feeds.blubrry.com/feeds/arrlontheair.xml

**Comment by kc2cbd** [comment] 2020-01-25 22:10
OK now with gPodder 3.10.12 I get this in the logs.

```
2020-01-25 16:02:42,858 [gpodder.sync] WARNING: Could not find gpod
2020-01-25 16:02:42,859 [gpodder.sync] WARNING: Could not find eyed3.mp3
2020-01-25 16:02:45,748 [gpodder.gtkui.desktopfile] WARNING: Parse HKEY error: HKEY_CLASSES_ROOT\Winamp.File\shell\Play\command ([WinError 2] The system cannot find the file specified)
2020-01-25 16:02:45,749 [gpodder.gtkui.desktopfile] WARNING: Parse HKEY error: HKEY_CLASSES_ROOT\Applications\foobar2000.exe\shell\open\command ([WinError 2] The system cannot find the file specified)
2020-01-25 16:02:45,749 [gpodder.gtkui.desktopfile] WARNING: Parse HKEY error: HKEY_CLASSES_ROOT\WMP11.AssocFile.MP3\shell\open\command ([WinError 2] The system cannot find the file specified)
2020-01-25 16:02:45,749 [gpodder.gtkui.desktopfile] WARNING: Parse HKEY error: HKEY_CLASSES_ROOT\QuickTime.mp3\shell\open\command ([WinError 2] The system cannot find the file specified)
2020-01-25 16:03:51,239 [gpodder.download] ERROR: _ssl.c:1091: The handshake operation timed out while downloading "Trailer Episode ARRL's On The Air Podcast": None
Traceback (most recent call last):
  File "request.py", line 1759, in open
  File "request.py", line 1968, in open_https
  File "request.py", line 1917, in _open_generic_http
  File "client.py", line 1230, in request
  File "client.py", line 1276, in _send_request
  File "client.py", line 1225, in endheaders
  File "client.py", line 1004, in _send_output
  File "client.py", line 944, in send
  File "client.py", line 1399, in connect
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
socket.timeout: _ssl.c:1091: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 863, in run
    headers, real_url = downloader.retrieve_resume(self.tempname, self.status_updated)
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 402, in retrieve_resume
    headers, real_url = downloader.retrieve_resume(url,
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 315, in retrieve_resume
    fp = self.open(url, data)
  File "request.py", line 1765, in open
  File "request.py", line 1759, in open
  File "request.py", line 1968, in open_https
  File "request.py", line 1917, in _open_generic_http
  File "client.py", line 1230, in request
  File "client.py", line 1276, in _send_request
  File "client.py", line 1225, in endheaders
  File "client.py", line 1004, in _send_output
  File "client.py", line 944, in send
  File "client.py", line 1399, in connect
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
OSError: [Errno socket error] _ssl.c:1091: The handshake operation timed out
```

I don't understand this.
I've never had any issues with gPodder before.
Still Windows 10 Home Version 1909 OS build 18363.592

Thanks
Dale

**Comment by kc2cbd** [comment] 2020-01-27 03:29
Apparently it is just https://blubrry.com/ that is causing the issues.

**Comment by elelay** [comment] 2020-02-16 15:36
OK, so I'm closing the issue.
Thanks,

**Closed by elelay** 2020-02-16 15:36 UTC
Labels: blocked, needs-confirmation, windows
