### ISSUE TITLE
gpodder stops responding when updating and downloading

### ISSUE THREAD

**Issue by ndias** [gpodder/gpodder#536] opened 2018-09-04 08:52 UTC
Since version 3.10 gpodder no longer respond (the user interface) when updating or downloading new episodes.

I downgrade to the gpodder-3.9.6 and every thing works fine and the UI doesn't freeze.

The last version I tested is gpodder-3.10.2-1.fc28 from the Fedora repository.

**Comment by elelay** [comment] 2018-09-06 06:16
I can't reproduce it.
Please run `gpodder -v` from command-line and report anything strange.
downloading and updating hase always been on a separate thread AFAICT.

**Comment by ndias** [comment] 2018-09-06 14:07
Hi,

 There are nothing strange in the terminal when running with -v

 Right now what I can see is gpodder using 100% of the CPU  

PID  USER  PR  NI VIRT   RES    SHR S   %CPU  %MEM TIME+   COMMAND     
5708 ndias 20  0  0.112t 178896 54504 S 100.0 1.8  23:08.24 gpodder

 When I tried to make a video about the problem, something strange
happens, gpodder is freeze, but when I use simplescreenrecorder to
record what is happen in gpodder (I choose to only record the window of
gpodder), gpodder starts to respond to the mouse.

 You can see that in the video https://youtu.be/nSPx-iILUrc

Cheers,
Nuno

On Wed, 2018-09-05 at 23:16 -0700, Eric Le Lay wrote:
> I can't reproduce it.
> Please run gpodder -v from command-line and report anything strange.
> downloading and updating hase always been on a separate thread
> AFAICT.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
-- 
Nuno Dias <Nuno.Dias@gmail.com>

**Comment by auouymous** [comment] 2018-10-01 12:42
It happens while downloading some new youtube videos. Downloading the "bad" video freezes gpodder, uses 100% cpu and requires a kill. This continues until the "bad" video is several hours older, and then it downloads fine.

**Comment by elelay** [comment] 2019-01-26 12:05
Fixed in 3.10.6

**Closed by elelay** 2019-01-26 12:05 UTC
