### ISSUE TITLE
Failed: I/O error: [SSL: CERTIFICATE_VERIFY_FAILED] certifcate verify failed (_ssl.c:661)

### ISSUE THREAD

**Issue by gpodderfan** [gpodder/gpodder#341] opened 2017-08-27 15:13 UTC
To begin, I want to say thx to the people involved in making this great podcatcher. I've been using it for over five years and it does all I want. Fabulous.

As I'm posting about a bug, obviously now I have a problem. From about six months ago, I've begun getting the following mesage when trying to download certain podcasts. It doesn't happen with all podcasts.

Failed: I/O error: [SSL: CERTIFICATE_VERIFY_FAILED] certifcate verify failed (_ssl.c:661): None - name of podcast

These are the feeds for two of the podcasts that this happens with.

https://feeds.feedburner.com/freakonomicsradio
https://rss.acast.com/ft-lucy-kellaway

This a feed that works just fine.

https://podcasts.files.bbci.co.uk/b006qykl.rss

It's now happening with about four or five podcasts. They didn't all throw up this message at the same time, but since getting that message, I've had to download podcasts manually for all of them that are affected. Always the same error message.

I've tried cancelling the subscription and resubscribing. No success. I've tried updating gpodder, both the portable and full install versions, to 3.9.3, no success.

After searching, it looks like a Python problem with certificates. I've tried updating Python to 2.7.13 and 3.4, the most uptodate that will work with Windows XP. No success. I've tried importing certifi into Python. No success. Though I may not have done this correctly as working with a command line is about at the limit of my computing skills. I would guess that the podcasts I've been having problems with, have begun using different certificates that don't work with Python. I've read about Python problems with OpenSSL and 2048 bit roots, but there haven't been any easy solutions online. If people have a solution that involves some command line work in Python, it would need to be spelt out step by step for me, as I have limited experience with that.

I had been playing about with Linux, a version of ubuntu, saw that I could download gpodder through the package manager, did that, and gpodder worked fine without any problems. 

However, would like to get it working in XP. I know, XP is old.

It may be you, (the people behind the program, if you manage this webpage), don't know about this problem. After searching it doesn't seem like anyone else has this issue. I've checked the mailing list back to 2015 and had a look through things here. I'd be surprised if it was just me. 

I've tried all I know, so now I'm hoping people can give a straightforward solution that will help me solve this and hopefully help anyone else who has the same problem.

**Comment by latepaul** [comment] 2017-11-24 11:13
I've hit this problem too. I'm running on Windows 10 and just reset my PC - which is basically wiping and re-installing Windows. I exported my subscriptions as an OPML file before I did so. After resetting the PC I reinstalled gpodder and imported the OPML. So it's kind of odd that I'm getting this error because I wasn't getting this problem before. 

It's like there's some dependency or setting that has changed but I don't know what it is.

**Comment by latepaul** [comment] 2017-11-24 12:36
I resolved this in the end by downgrading to python 2.7.5 - see [here ](https://interset.zendesk.com/hc/en-us/articles/115011874548--SSL-CERTIFICATE-VERIFY-FAILED-certificate-verify-failed-ssl-c-579-)

**Comment by gpodderfan** [comment] 2017-12-08 07:24
Appreciate the response. I downloaded Python 2.7.5 and 2.7.4 for Windows from the Python website. That didn't work for me. As before, some podcasts will download, but some others will not, bringing up the certificate verify failed message. 

I had a look at the link you gave. The info there talks about a 2.7.5-48 build from February 2017. There is only one version of Python 2.7.5 for windows on the website to download and it's not a build from 2017, it's from May 2013. Did you get the 2.7.5 version of Python from the same place I got it, the link below, or from somewhere else?

https://www.python.org/download/releases/2.7.5/

Thanks!

**Comment by maspa05** [comment] 2017-12-08 11:12
I used the versions from python.org. 

I didn't look in detail at what's on that page, it's just what tipped me off that an earlier version might work.

Actually I meant to come back and update this issue because it wasn't quite so straightforward. I did get it working with 2.7.5 but then there was another problem - I can't remember what it was now. All I remember was that I thought it was due to downgrading python so what I ended up doing was trying to find a version that would fix both. 

So I downloaded all the versions between 2.7.5 and the one I'd started on (2.7.12 I think) and went through trying to find one that was optimum. I was careful to uninstall the previous version before installing and testing the next. I was also re-installing pygtk but I can't remember if I also re-installed gpodder itself. Maybe the first couple of times. 

I figured I would find the point where it stopped working again. But.. it kept working, even when I re-installed the version I'd started with. I figured maybe that was because once the certificate is verified that info is cached somewhere, somewhere that's not affected by me uninstalling/re-installing python. I decided however to just keep an eye on it and see if it re-surfaced. So far it hasn't.

**Comment by maspa05** [comment] 2017-12-08 11:13
Just realised I am logged in to my work account. But I am also 'latepaul'.

**Comment by gpodderfan** [comment] 2017-12-15 10:14
Thanks maspa05 and latepaul! Glad you found a solution that seems to be working for you. It's the best podcaster that I've come across, so I'll keep looking for something that works for me.

**Comment by codyolsen** [comment] 2018-03-28 19:12
Also getting this error on https://feeds.feedburner.com/freakonomicsradio using os x 3.10.1

**Comment by Aliceenligne** [comment] 2018-04-04 21:50
I did get the same error message, also after resetting my Windows 8.1 PC.
I have it with all podcasts from www.arteradio.com.
On my online subscriptions they seem to work fine though.

Regarding freakonomicsradio, I did get a message but not the same (the error identification part was blank) and it did charge on my computer, only in a new section called "other" (the first and only previous one being "audio")

I hope this help someone to identify and resolve the problem because I am clueless !

**Comment by elelay** [comment] 2018-09-09 19:47
Closing as too dependent on network + computer setup.
Following a survey on gpodder mailing list, no reproduce from many users.
Also windows situation is improved by 3.10.4 because gPodder won't load old ssl libraries installed by other programs in Windows directory

**Closed by elelay** 2018-09-09 19:47 UTC
Labels: blocked, windows
