### ISSUE TITLE
Package gpodder-adaptive

### ISSUE THREAD

**Issue by thomasgoirand** [gpodder/gpodder#1218] opened 2022-02-01 23:20 UTC
Hi,

I used to use gPodder on my Nokia n900, and I was very happy with it. This was 10 years ago.

Now, I just bought a brand new Pinephone Pro. gPodder from Debian looks like working unmodified, however, its GUI isn't adapted to smaller screen, and I cannot reach buttons on the right.

Please allow resizing to a (very) small width and make the interface adaptative for such mode.

**Comment by auouymous** [comment] 2022-02-01 23:59
There is an adaptive branch at https://github.com/gpodder/gpodder/tree/adaptive. I don't know if there is a package anywhere for it, or if you will need to install it from source.

**Comment by tpikonen** [comment] 2022-02-02 07:45
I was / am planning to make a separate flatpak for the adaptive branch after the next gpodder release. That has taken more time than I expected, but I'll get to it eventually. Running from the source tree works fine though.

BTW @auouymous, I would like to see the UI-cleanups from #1188 merged before next release. They are also a prerequisite for bringing the adaptive and master UI's closer to each other, easing maintenance. Could you have a look at them?

**Comment by tpikonen** [comment] 2022-02-02 07:54
I hijacked this issue to track the flatpak packaging of the adaptive gpodder branch. PostmarketOS / Alpine Linux already have  a [package](https://gitlab.alpinelinux.org/alpine/aports/-/tree/master/community/gpodder-adaptive).

**Comment by Maryjane-ai** [comment] 2022-06-01 01:46
Is the intention to merge the adaptive version of gpodder into the main branch. Or will it end up having two versions of gpodder?

**Comment by auouymous** [comment] 2022-06-01 02:57
@Maryjane-ai We are merging as much as possible to make maintenance of the adaptive branch easier. Ideally the main branch would detect libhandy and use an adaptive UI, but that might complicate the code and make the project harder to maintain. However, if #1136 is ever finished, it might make a full integration possible.

**Comment by tpikonen** [comment] 2022-06-02 18:05
@Maryjane-ai I'm mostly waiting for a new main branch gPodder release to base a new adaptive release to something stable.

A version of the adaptive gPodder with more recent changes from the main branch is occasionally pushed [here](https://github.com/tpikonen/gpodder/tree/dev-adaptive).

**Comment by Maryjane-ai** [comment] 2022-06-06 04:34
@auouymous @tpikonen thank you for this information. I made some months ago a deb package of the adaptive branch so that I could install it on my mobile device, and posted it [here](https://git.disroot.org/maryjane/gpodder-adaptive-deb-package).

I am glad that there is a perspective of when possible to make gPodder main adaptive. 

gPodder is an awesome tool and thank you all for your work.

**Comment by tpikonen** [comment] 2022-07-16 16:26
> So, any progress on merging the code?

It would be nice to have something like a command line switch to change the user interface from classic to adaptive, but the code in the adaptive branch has sort of drifted into the other direction recently, with small patches on top of the classic ui, instead of separate code and ui files.

Nevertheless, this would be possible, if the maintainers agree on adding some amount of ui-conditional code blocks (e.g. `if adaptive: do_this, else: do_that`) to the master branch. The largest practical problem is `main.py` which is in a serious need of refactoring and currently has a cool 1400 line diff between master and adaptive.

There is probably going to be some unification of the `main.py` code after the next release (context menus, for example), so let's see how small the delta will get. Refactoring the channel and episode list code in `main.py` to different files is on my long term todo list, but that will take a while.

**Comment by thomasgoirand** [comment] 2022-07-31 22:07
Hi. I agree nearly all of the above, though I don't think a command line switch is a sensitive thing to do. There's smarter things to do, like simply using the size of the main window as condition.

**Comment by auouymous** [comment] 2022-08-01 05:43
@thomasgoirand My gpodder window is 672x646, would I be forced to use adaptive? Don't phones have 1080p or greater resolution? Would gpodder switch between classic and adaptive when the user rotates their phone between landscape and portrait?

Anyone with libhandy installed probably wants adaptive, so detecting it should work fine.

**Comment by ollieparanoid** [comment] 2022-08-02 21:23
Congratulations to everybody on the new gpodder release!

@tpikonen: happy to see that you're still maintaining the adaptive version and rebased it on 3.11.0! I'm still using gpodder almost every day on my phone with the adaptive patches.

I just checked out your dev-adaptive branch and gave it a quick try, it seems to behave pretty much the same as what I used before (adaptive/3.10.21+1 with #1105 and #1106).

Can an official adaptive/3.11.x tag get created so distros can package it? I'm maintaining these alpine/pmOS packages of gpodder and gpodder-adaptive.

Of course merging the branch into the official one would be great at some point in the future. Regarding the discussion of command-line switch or not; having an option to override whatever autodetection is used seems very useful, so I'd suggest to add that.

**Comment by tpikonen** [comment] 2022-08-03 04:26
> Can an official adaptive/3.11.x tag get created so distros can package it? I'm maintaining these alpine/pmOS packages of gpodder and gpodder-adaptive.

I have some small UI-fixes in the works which I want to include in the next adaptive release. I'm mostly offline for the next week though, so this will take a while.

**Comment by tpikonen** [comment] 2022-08-24 15:02
Ok, the [dev-adaptive tree](https://github.com/tpikonen/gpodder/tree/dev-adaptive) now has a release candidate version ready. Please test this, if you are interested. If there are no problems, I'm going to push this to the adaptive branch and tag it as a release in a few days.

With the latest UI-fixes (hint: swipe down) I'm pretty happy with the interface. Real swipes through GtkTreeViews would be nice, but this would require patching GTK.

The remaining problem (in addition to the bugs also in master branch) is performance. With the original Pinephone and 4k episodes, switching to 'All episodes' takes +20 seconds to complete, and burns almost 2 minutes of full CPU to compute the TreeView model. Switching away from 'All episodes' takes almost as long, so it's best to run gPodder with the 'All episodes' and 'sections' options set to off. I think some cython in selected code paths would help a lot, but I currently don't have much time to investigate this.

After the release, I'll look into submitting a package to flathub.

**Comment by ollieparanoid** [comment] 2022-08-25 07:52
> Ok, the [dev-adaptive tree](https://github.com/tpikonen/gpodder/tree/dev-adaptive) now has a release candidate version ready. Please test this, if you are interested. If there are no problems, I'm going to push this to the adaptive branch and tag it as a release in a few days.

Checked the sources out now, will report if I find any problems. looking good so far!

> With the latest UI-fixes (hint: swipe down) I'm pretty happy with the interface. Real swipes through GtkTreeViews would be nice, but this would require patching GTK.

Nice addition with the swipe down menu.

> The remaining problem (in addition to the bugs also in master branch) is performance. With the original Pinephone and 4k episodes, switching to 'All episodes' takes +20 seconds to complete, and burns almost 2 minutes of full CPU to compute the TreeView model. Switching away from 'All episodes' takes almost as long, so it's best to run gPodder with the 'All episodes' and 'sections' options set to off. I think some cython in selected code paths would help a lot, but I currently don't have much time to investigate this.

Interesting, I cannot reproduce this. For me the "all episodes" page opens almost instantly, maybe waiting a few seconds if doing it for the first time after starting gpodder but definitively not 2 min at 100% cpu usage. Also running on the original pinephone with around 4k episodes. I wonder if it relates to the downloaded episodes? I relatively quickly delete them after listening to them, currently I have 29 downloaded episodes.

(Also a minor thing I found, tapping on "Audio" actually opens all episodes even if the option is disabled. Not really important though.)

Thanks a lot @tpikonen!

**Comment by ollieparanoid** [comment] 2022-08-25 15:18
I've noticed that when having a podcast show open (the view that shows the episodes of one podcast) and swiping down, it goes back to the previous screen. It would be nice if it worked similar to when swiping down on the listing of podcasts, where one gets an option to update all podcasts. so in this case it would only update that one podcast that's open. is that possible?

Regarding "all episodes", it's still a lot faster than you described. but I do notice that also after opening it, and going back to the main menu, it seems to hang / can't open another show immediately. I wonder if the background process that is rendering the previous listing could be stopped at that point. (probably not feasible for this release, and that's fine)

**Comment by tpikonen** [comment] 2022-08-25 17:47
> It would be nice if it worked similar to when swiping down on the listing of podcasts, where one gets an option to update all podcasts. so in this case it would only update that one podcast that's open. is that possible?

The major problem with GtkTreeViews, which gPodder uses everywhere, is that they do not pass swipe gestures to the containers below. The swipe-down to go-back hack removes the need to tap the very small back button on the upper left corner. You can update a single podcast by long-pressing it on the channels view and selecting the update option from the context menu.

BTW, the adaptive UI should now be feature complete, so if there is something you can do in the master-branch gPodder, but not in adaptive, please let me know.

I timed the transitions from 'All episodes' again, and it's about 10 seconds to and from. Changing from the 'All' view to 'Downloaded' in 'All episodes' takes almost 20 seconds. The CPU is at 100 % for more than a minute after switching to 'All episodes'.

**Comment by auouymous** [comment] 2022-08-26 06:46
> I timed the transitions from 'All episodes' again, and it's about 10 seconds to and from. Changing from the 'All' view to 'Downloaded' in 'All episodes' takes almost 20 seconds. The CPU is at 100 % for more than a minute after switching to 'All episodes'.

@tpikonen Could you install the stack dumper extension, modify it to use 1 second intervals instead of 10, and see where it spends the time?

https://github.com/gpodder/gpodder/issues/550#issuecomment-440410763

**Comment by ollieparanoid** [comment] 2022-08-29 07:04
> You can update a single podcast by long-pressing it on the channels view and selecting the update option from the context menu.

Aaah I didn't know that, thanks!

**Comment by tpikonen** [comment] 2022-08-30 07:27
Ok, since there were no obvious bugs, I've now tagged and pushed the 'adaptive/3.11.0+1' version to the [adaptive branch](https://github.com/gpodder/gpodder/tree/adaptive).

**Comment by tpikonen** [comment] 2022-09-09 08:37
The adaptive gPodder is now available on flathub: https://flathub.org/apps/details/org.gpodder.gpodder-adaptive Yay!

I'm closing this bug, but please open another one for further packaging issues, if necessary.

The performance problems also deserve an issue of their own, I'll open one when I get some profiling done.

**Closed by tpikonen** 2022-09-09 08:37 UTC
Labels: flatpak, adaptive
