### ISSUE TITLE
BUG As a user[0], when I add a podcast RSS feed, I want to see the latest podcast episodes

### ISSUE THREAD

**Issue by ldexterldesign** [gpodder/gpodder#314] opened 2017-06-10 17:04 UTC
Hi all,

Thanks for software

Hope you're well

BUG As a user[0], when I add a podcast RSS feed to https://gpodder.net/missing/ , I want to see the latest podcast episodes

Screen shot(s)/cast:

<img width="1440" alt="screen shot 2017-06-10 at 19 02 34" src="https://user-images.githubusercontent.com/1715809/27004765-95d24d18-4e0f-11e7-8292-95b156a24709.png">
<img width="1440" alt="screen shot 2017-06-10 at 19 02 48" src="https://user-images.githubusercontent.com/1715809/27004769-95d8ba40-4e0f-11e7-95ca-5d61b745466e.png">
<img width="1440" alt="screen shot 2017-06-10 at 19 03 09" src="https://user-images.githubusercontent.com/1715809/27004766-95d58032-4e0f-11e7-83fd-1249cbf76b05.png">
<img width="1440" alt="screen shot 2017-06-10 at 19 03 16" src="https://user-images.githubusercontent.com/1715809/27004767-95d60e08-4e0f-11e7-884f-3348bb20b68e.png">
<img width="1440" alt="screen shot 2017-06-10 at 19 03 20" src="https://user-images.githubusercontent.com/1715809/27004770-95d91ef4-4e0f-11e7-9203-2c95e8cf4730.png">
<img width="1440" alt="screen shot 2017-06-10 at 19 03 25" src="https://user-images.githubusercontent.com/1715809/27004768-95d6c6ea-4e0f-11e7-832f-39265ea11c4b.png">

If anyone else reading this agrees please up-vote or reply "+1"

I'll follow up again in the near future and base my decision to keep using https://gpodder.net/ on whether it's been fixed

Please let me know if there's a more suitable place to leave issues

Hope to hear back

Yours faithfully

[0]
Device: Apple MacBook Pro
Platform: OS X 10.12.5 (16F73)
Browser: Vivaldi 1.9.818.50 (Stable channel) (64-bit)

**Comment by adamvoss** [comment] 2017-06-10 17:17
Duplicate of #260

**Closed by adamvoss** 2017-06-10 17:17 UTC

**Comment by ldexterldesign** [comment] 2017-06-12 16:16
@adamvoss thanks for reply

If I install locally is the same issue likely to persist?

Hope to hear back

Yours faithfully

**Comment by adamvoss** [comment] 2017-06-12 16:25
I'm not sure I understand your use case to know if running your own copy would meet your needs.  I have not worked with it, but I imagine that would give you the service without any dataset.  You would first need to populate the system with podcasts.  If you need to populate the system with desired podcasts, then couldn't you just use gPodder or any other podcast client to read the desired feeds?

**Comment by ldexterldesign** [comment] 2017-06-12 16:34
My use case is I consume podcasts on mobile using https://play.google.com/store/apps/details?id=de.danoeh.antennapod

I would like to reference the same feed on web (i.e. http://gpodder.net ) so I can update my ratings table[0]

http://player.fm (free, but currently has bugs) and then http://pocketcasts.com (paid, but lacks the feature I need[1]) are two softwares I've been using, but now researching other options again

Hope this is clear/useful and to hear back

Thanks

[0] https://docs.google.com/spreadsheets/d/1xZG8KFsaeAHHPe4pQejyiqTQufyE_DWGB6m2C3mt0o4/edit#gid=1798460493
[1] https://twitter.com/ldexterldesign/status/872448134533787652

**Comment by elelay** [comment] 2017-06-12 21:20
I was able to install my own instance of mygpo.
Unfortunately, I wasn't interested in the web ui at the time, and didn't setup feed refreshes, so I can't help you in configuring that.

**Comment by ldexterldesign** [comment] 2017-06-13 10:24
@adamvoss thanks for https://github.com/gpodder/gpodder/issues/260#issuecomment-307841669

Can I confirm the expected behaviour of the software *is* to have updated feeds (I do see the bug status) and may I ask how you're currently using gpodder?

Yours hopefully

**Comment by adamvoss** [comment] 2017-06-13 14:35
@ldexterldesign  I am not a developer of gpodder.net/mygpo, but I have high confidence that the feeds listed on the website are meant to update.  Given https://github.com/gpodder/gpodder/issues/260#issuecomment-307932824, it sounds like you are welcome to try deploying your own copy of gpodder.net/mygpo and seeing if it works and report back, but I do not know of anyone that has investigated the issue to be able to answer your question of if a local deployment would have the issue.

Regarding how I use gPodder, I launch it when I want to update feeds and download new episodes.  I typically have it send episodes to my mp3 player, but sometimes listen directly from the computer.  I have gPodder.net integration turned on to sync my subscriptions, but at this point that is really only so I count against the subscriber numbers on gPodder.net and not because I need its backup/sync.  I essentially never visit gpodder.net.

**Comment by ldexterldesign** [comment] 2017-06-13 21:03
Thanks, will have to keep an eye on https://github.com/gpodder/gpodder/issues/260 and hope it gets fixed

In the meantime will have to make do[0] and love to hear cross platform (e.g. web and Android) podcast alternatives..?

Cheers

[0] https://github.com/gpodder/gpodder/issues/314#issuecomment-307844182
