### ISSUE TITLE
error 22 invalid argument on seemingly random episodes

### ISSUE THREAD

**Issue by jadekitten** [gpodder/gpodder#591] opened 2019-01-13 22:30 UTC
i'm on gpodder 3.10.6 on win10/x64  example  https://snag.gy/Po63GL.jpg  https://snag.gy/aznOev.jpg

**Comment by elelay** [comment] 2019-01-17 07:55
That's a bug. Thanks for reporting.

**Comment by jadekitten** [comment] 2019-01-19 17:11
debug console window output https://pastebin.com/QRm8HeZL I verified 3.10.6

**Comment by jadekitten** [comment] 2019-01-26 01:34
hello????

**Comment by elelay** [comment] 2019-01-27 10:36
Sorry: your answer fell into the cracks...
Thanks for the trace.

With it I was able to reproduce: the rss feed I tried it was http://lpotl.libsyn.com/rss, while you use http://feeds.soundcloud.com/users/soundcloud%3Ausers%3A137846288/sounds.rss

I shall be able to come up with a solution soon.

**Comment by elelay** [comment] 2019-01-27 11:31
This is due to the server sending a wrong Content-disposition filename for some files:
correct: Episode 346: Mark Twitchell Part I - Favorite Duck of the Month
=> Content-Disposition: attachment;filename="LPOTL346FINAL_mixdown.mp3"
incorrect: Side Stories: Cannibal Corpse Rapture
=> Content-Disposition: attachment;filename="SS_CannibalCorpseRapture.mp3?dest-id=754182"

**Comment by elelay** [comment] 2019-01-27 11:31
I've fixed it in

**Comment by elelay** [comment] 2019-02-02 08:03
Fixed in 3.10.7

**Closed by elelay** 2019-02-02 08:03 UTC
Labels: bug, fixed-in-master
