### ISSUE TITLE
"completed" videos downloaded from youtube are all 0 byte files

### ISSUE THREAD

**Issue by vvilkommen** [gpodder/gpodder#1427] opened 2022-10-27 05:34 UTC
gpodder 3.11.0
windows 10 

tl, dr; 
- gpodder (youtube-dl) extension downloads entire videos (per download progress UI, at least), but upon completion, the final file is 0 bytes and fails to open.
- toggling settings > extensions > youtube-dl off then back on allows downloaded videos to work again
-  however, downloading breaks (ie downloaded youtube videos are all 0 byte again) after gpo checks for new episodes (it seems, perhaps coincedence, but seemed to affect the issue every time)
- a few interesting things:
- - my download folder is a junction to another location, but this doesn't affect non-youtube podcasts
- - checking for new episodes on my gpo box causes the program to hang for a minute or so (it's always been this way, there are a lot of feeds to check) so this problem may be a coincidence that happens due to extended hang?
- - i have no idea where the error logs are kept, but the 0 byte failures are silent (ie no modal error windows)

details:

I have been using gpodder to manage several youtube channels, but today I tried to open a file and it didn't work. So I went to the download folder and saw they are all 0 byte files! And in those channel folders, it looks like 0 byte videos have been downloaded (by sorting the folder by date added) since I upgraded gpodder to 3.11.0.

So I opened gpodder settings > extensions, then toggled off "youtube-dl," the toggled it back on. Then I deleted an affected episode and re-downloaded it from the gpo context menu. It downloaded fine, then ran. After a while, the problem happened again: gpo 0 bit the youtube videos. the setting toggle worked. downloading worked again. 

then i noticed that gpo automatically checks all podcasts for updates, and after that youtube download functionality is broken again. 

What do you think?

**Comment by vvilkommen** [comment] 2022-10-27 05:47
-- oh and this seemed to happen if gpo tried to download multiple videos, the first video downloaded was made 0 byte.

still trying to test this out.

**Comment by auouymous** [comment] 2022-10-27 07:03
The `Logs` folder can be found at https://gpodder.github.io/docs/user-manual.html#default-gpodder-home-folder.

This might be caused by #1360. Do you the non-empty files exist in your Documents folder?

**Comment by vvilkommen** [comment] 2022-10-27 22:22
Ah yes! The non-empty files, many, perhaps all of them, are in data/bin in the default youtube-dl naming format videoname [videocode].ext. Perfectly watchable, but all in data/bin, while the 0 byte gpo-renamed version of the files are in the expected location instead.

**Comment by auouymous** [comment] 2022-10-27 22:44
> It is interesting that toggling the youtube-dl setting in extensions "fixes" the issue for a time or so.

Weird, not sure why that would do anything. Anyway, closing the issue, feel free to subscribe to #1360 for updates on its progress.

**Closed by auouymous** 2022-10-27 22:44 UTC

**Comment by vvilkommen** [comment] 2022-10-29 03:40
Sure thing
