### ISSUE TITLE
Tagging extension broken on Manjaro 16.10

### ISSUE THREAD

**Issue by jstagge** [gpodder/gpodder#154] opened 2016-10-24 13:35 UTC
Since updates over the past 2 months, the tagging extension does not appear to be working properly. For instance, after download, the genre is not changed to the default.

I have tried modifying the code, but cannot locate the problem.  Here are the versions I am using:
- gpodder 3.9.1
- mutagen 1.34.1-1
- python 3.5.2

I have tried downgrading my mutagen with no luck.  Any help would be greatly appreciated!

**Comment by thp** [comment] 2016-10-24 13:38
Did you try this fix? https://github.com/gpodder/gpodder/commit/a87609ccdc1a5907c4f59e34927e861f13a7aa10

**Comment by jstagge** [comment] 2016-10-24 13:46
I have tried this new file.

**Comment by thp** [comment] 2016-12-18 12:08
Is there any way to reproduce this problem easily (step by step instructions, including feed, and settings and what to expect and what is actually happening)?

**Comment by elelay** [comment] 2018-07-22 08:57
Closing issue because it's been blocked for too long.

**Closed by elelay** 2018-07-22 08:57 UTC
Labels: bug, needs-confirmation
