### ISSUE TITLE
AttributeError: type object 'SeparatorMarker' has no attribute 'get_statistics'

### ISSUE THREAD

**Issue by wdenton** [gpodder/gpodder#985] opened 2021-03-19 15:01 UTC
After #981 was fixed (thanks!), I enabled sections and categorized some podcasts, then decided I liked it fine without sections, so I disabled the option.  Then I got this error in a popup: 

    Unhandled exception: Please report this problem and restart gPodder:
    type object 'SeparatorMarker' has no attribute 'get_statistics'

The full error is:

```
1616164706.258846 [gpodder.gtkui.main] ERROR: Exception happened while updating download list.
Traceback (most recent call last):
  File "/usr/local/src/gpodder/src/gpodder/gtkui/main.py", line 1245, in update_downloads_list
    self.update_podcast_list_model(channel_urls)
  File "/usr/local/src/gpodder/src/gpodder/gtkui/main.py", line 2319, in update_podcast_list_model
    self.podcast_list_model.update_by_urls(urls)
  File "/usr/local/src/gpodder/src/gpodder/gtkui/model.py", line 877, in update_by_urls
    self.update_by_iter(row.iter)
  File "/usr/local/src/gpodder/src/gpodder/gtkui/model.py", line 903, in update_by_iter
    total, deleted, new, downloaded, unplayed = channel.get_statistics()
AttributeError: type object 'SeparatorMarker' has no attribute 'get_statistics'
```

It caused some strange behaviour with the UI freezing while downloads continued, I think.

**Comment by elelay** [comment] 2021-03-19 17:58
I hope I pushed a fix for the issue. I couldn't reproduce it (neither #981) so honestly it can still be there...

**Closed** 2021-03-19 17:58 UTC

**Comment by auouymous** [comment] 2021-03-20 02:52
I was able to reproduce #981 but I also can't reproduce this one.

@wdenton reopen this issue if it isn't fixed, and provide some steps that cause it..

**Comment by wdenton** [comment] 2021-03-20 03:29
@elelay @auouymous It's gone now. Thanks!
