### ISSUE TITLE
No podcasts have been updated since upgrading from 3.91 to 3.92

### ISSUE THREAD

**Issue by Swagger200** [gpodder/gpodder#182] opened 2016-12-05 05:20 UTC
And I cannot go back to 3.91 (python error). I have changed no settings. I just want to download all the podcasts, all the time, whenever they are available.

**Comment by Swagger200** [comment] 2016-12-05 05:21
I keep checking and it keeps finding no updates, I know full well that many are updated daily and am not getting these.

**Comment by matoro** [comment] 2016-12-05 07:40
@Swagger200 are you sure you have it configured correctly?  Can you post your settings.json?

**Comment by Swagger200** [comment] 2016-12-05 12:30
Not sure where to find that file?

**Comment by matoro** [comment] 2016-12-05 15:40
Should be wherever you have your gpodder data stored.  On Linux, try ~/gPodder, on Windows check %APPDATA%.

**Comment by Swagger200** [comment] 2016-12-06 00:00
I am on Windows - I can't see any gpodder folder or settings.json under %APPDATA%

**Comment by Swagger200** [comment] 2016-12-06 00:04
It was working mostly OK on 3.91 - at least it was updating podcasts as it should. Have downloaded over 300gb of podcasts. Since 3.92 (5 days) nothing. It keeps checking and finding nothing to do. I see this new message "Episode actions from gpodder.net are merged" - is that an indicator?

**Comment by matoro** [comment] 2016-12-06 01:15
My bad, check under your home directory (I believe it should be C:\Users\<your username>\gPodder).  Can you upload the settings.json from there?

**Comment by Swagger200** [comment] 2016-12-06 02:26
It wasn't there, but I searched my whole PC and found it in the folder where podcasts are downloaded/ 
[Settings.zip](https://github.com/gpodder/gpodder/files/632831/Settings.zip)

**Comment by matoro** [comment] 2016-12-06 04:58
Hmm, don't see any major settings differences.  Have you tried clearing out all the files you want to keep and starting fresh?

**Comment by Dabrinko** [comment] 2016-12-06 13:45
Hello! 

I also get no new files downloaded. Using the "Update podcast" or the "Search for new episodes" button produces the same result. It just zips through the process and nothing is downloaded. It just says "No new episodes" (there are, I've checked with my mobile pod app)

Attaching settings file as well.
[Settings.zip](https://github.com/gpodder/gpodder/files/633982/Settings.zip)

**Comment by thp** [comment] 2016-12-06 13:54
For which feeds (URL) is this happening?

**Comment by Dabrinko** [comment] 2016-12-06 13:55
All of them? I guess I could send a list of them. Are they stored anywhere?

**Comment by Swagger200** [comment] 2016-12-06 19:08
I have 46 podcasts set up. None of them are updating.

**Comment by vossad01** [comment] 2016-12-12 04:13
A little while back I had issues with moving my gPodder DB from a Windows install to a Linux install.  There may have been a version change in there too, I'm not sure.  However it happened, it resulted in me getting a bunch of duplicated episodes because how the episode 'guid' was being created.

That is relevant because I found this handy tool when I wanted to fix it: [DB Browser for SQLite](http://sqlitebrowser.org/)

I don't know if this will fix it, but what you describe behaves symptomatically the same as something I encountered while hacking in the database.  Still, make a backup before doing this, no warranty, etc.

 - Install DB Browser for SQLite
 - Ensure gPodder is not running
 - Find your gPodder home directory (should be the same place your settings.json came from) 
 - Backup 'Database'
 - Open DB Browser for SQLite
 - Open 'Database' in DB Browser for SQLite.  In the "Open database..." dialog you will need to change "Files of type:" to "All Files" to see it.
 - Go to the "Browse Data"
 - Select the table "podcast" from the drop down
 - Find the `http_last_modified` and `http_etag` columns
 - Delete all entries in those columns (you can select them all and press delete once)
 - Write the changes to the database (there is a button)
 - Close DB Browser for SQLite
 - Launch gPodder and try to update your podcasts

The columns I had you clear control two different ways gPodder keeps track of already having looked at a feed.  By clearing the entries them you force it to completely check the feed rather than just checking if it things the feed has been updated since it was last checked.

Hopefully the above works for you.  If it does not more information will be needed to figure out what the problem is.

**Comment by Dabrinko** [comment] 2016-12-12 09:20
I tried the above solution and it didn't work. I made sure that I followed all your steps.

I also, on a whim, added the gpodder.exe to be allowed through the windows firewall, no changes.

Hopefully this will be sorted out soon.

**Comment by vossad01** [comment] 2016-12-12 21:55
Sorry to hear that, thanks for giving it a try.  Here are some things that can help with getting to the bottom of the issue:

 * Launch gPodder from a terminal/command prompt.  Perform the update action.  Check the terminal/console window to see if there is any output.  If we are lucky (in some sense of the word) we will see an exception there that indicates where the application has encountered an issue.
 * If you are willing, provide the podcasts you are are subscribed to in order to see if the issue can be reproduced for other users.  Given what has been reported I am not convinced it is a feed issue, but also good to rule it out.  For convenience, You can use the DB Browser you already installed to get the feed urls from the "url" colum of the "podcast" table.

**Comment by vossad01** [comment] 2016-12-16 04:42
@Dabrinko Thanks!  With the exception you show in the log, I am hopeful someone will be able to dig into this and find a resolution.  I'm traveling with limited connectivity through the end of the year, so that person probably won't be me.

**Comment by Dabrinko** [comment] 2016-12-16 09:10
Thank you for your assistance @vossad01!

**Comment by thp** [comment] 2016-12-17 10:08
@Dabrinko that attached gpoError.txt is actually really helpful, I'll get around to look into that issue soon :)

**Comment by thp** [comment] 2016-12-17 11:08
![screen shot 2016-12-17 at 12 07 24](https://cloud.githubusercontent.com/assets/135241/21286346/699369e6-c451-11e6-9561-9500c4345a69.png)

@Dabrinko Does your database schema look like this? (note that `http_last_modified` and `http_etag` both have their type set to `TEXT`) Can you also send a screenshot of the current column values for your podcasts? Does setting those values to `NULL` fix the issue?

**Comment by thp** [comment] 2016-12-18 12:05
This should be fixed with the latest code from the master branch. Please reopen if you are still experiencing issues there.

**Closed by thp** 2016-12-18 12:05 UTC

**Comment by vossad01** [comment] 2016-12-21 01:22
> Does your database schema look like this? (note that http_last_modified and http_etag both have their type set to TEXT) Can you also send a screenshot of the current column values for your podcasts? Does setting those values to NULL fix the issue?

Shoot, I forgot that you needed to press the "Set as NULL" button not just delete entries to get NULL.  Hope I didn't cause the issue that was reported in the error log.

**Comment by Dabrinko** [comment] 2016-12-21 07:29
Setting the values to NULL as described doesn't help the original issue. I'm going to wait for the next release, I think.

**Comment by vossad01** [comment] 2016-12-21 16:03
Could you check the terminal (command line) output after having set the
values to NULL?  Actually, instead of that, could you restore the backup
from before you modified the database and check the output on that?  I am
just hoping to maximize the chance that your original issue is fixed in the
next version.

**Comment by Dabrinko** [comment] 2017-01-09 14:58
Hello! Back at the computer where gPodder is. Latest version (3.93) solved this issue for me.
