### ISSUE TITLE
GPodder Micro-Crash 

### ISSUE THREAD

**Issue by Chrits55** [gpodder/gpodder#1437] opened 2022-11-09 21:26 UTC
it's Gpodder 3.11 running on Windows 11  

when you open GPodder the application part-crashes 

the task bar icon shows up ... but when you click it to show the GPodder window open on the desktop .. it does nothing...  the task bar icon says there's a GPodder window open but when you click it to bring it to the desktop full size .. it's not there ... and yes i've  tried the Run as Administrator option.... same problem

**Comment by auouymous** [comment] 2022-11-09 22:32
Can you look at https://gpodder.github.io/docs/user-manual.html#default-gpodder-home-folder, and paste any errors from the current log file in the Logs directory?

**Comment by Chrits55** [comment] 2022-11-11 18:44
i can't??.. going to try a reinstall

**Comment by ImMrDC** [comment] 2022-12-13 10:21
I'm getting the same issue on win10. Tried reinstalling and running as admin. Can't think of anything changing - worked yesterday. Get the following in logs after opening:
`2022-12-13 10:19:04,061 [gpodder.gtkui.desktopfile] WARNING: Parse HKEY error: HKEY_CLASSES_ROOT\Winamp.File\shell\Play\command ([WinError 2] The system cannot find the file specified)
2022-12-13 10:19:04,061 [gpodder.gtkui.desktopfile] WARNING: Parse HKEY error: HKEY_CLASSES_ROOT\Applications\foobar2000.exe\shell\open\command ([WinError 2] The system cannot find the file specified)
2022-12-13 10:19:04,062 [gpodder.gtkui.desktopfile] WARNING: Parse HKEY error: HKEY_CLASSES_ROOT\QuickTime.mp3\shell\open\command ([WinError 2] The system cannot find the file specified)
`

**Comment by auouymous** [comment] 2022-12-13 11:02
@ImMrDC Those warnings are normal "noise", ignore them.

Could you try upgrading to https://ci.appveyor.com/project/elelay/gpodder/builds/45639042/artifacts? This issue might be a duplicate of #1352 which was fixed by #1356.

**Closed** 2023-01-27 00:46 UTC
