### ISSUE TITLE
Remembering where I stopped

### ISSUE THREAD

**Issue by ShaiGerbi** [gpodder/gpodder#786] opened 2020-04-23 19:43 UTC
Many times I want to keep listening to a podcast at a later date 
and I have no convenient option to record the minute I stopped

I think it is worth adding the "Remember time" button
By right clicking on the chapter
Opens a window with the option to enter time
And in the podcast list will be an indication of time

**Comment by auouymous** [comment] 2020-04-23 22:33
There are players that will do this for you. Panucci for Maemo devices does it. You could check if your player has the feature or find one that does.

Gpodder could have a 'notes' field on each episode with a popup to edit it. The notes could be displayed in the episode tooltip. Or maybe a third row added to episodes that have notes, which is better for touch screens that don't have tooltips. Someone needs to want it enough to add the feature.

**Comment by dovf** [comment] 2020-04-23 23:35
You may find this plugin useful: https://gpodder.github.io/docs/extensions/mprislistener.html (full disclosure: I created it; also, I'm still using a really old version of gPodder, I hope the plugin still works with more current versions, but I haven't really checked lately...)

**Comment by coffee-lord** [comment] 2020-04-24 10:07
@dovf, thank you for the plugin! However, I have a question: 

Whenever I close VLC or switch to a different episode, the plugin marks the episode as "Finished" when it clearly isn't. Is that intended behavior?

**Comment by dovf** [comment] 2020-04-24 11:47
It doesn't sound intended, but I'm not sure I understand exactly the behavior you're describing (and again, I'm using a really old version of gPodder, and haven't touched the code in years, so I don't know how much is relevant to current gPodder, or how much I can help here, but I'll try):
* Firstly, do you see that last played position in the episode listing? (It should be displayed as part of the "duration" field -- you may need to enable it in View -> Visible columns. When visible, the duration field should display just the duration ("yy:yy") for unplayed episodes, "xx:xx/yy:yy" for partially played episodes, or "Finished (yy:yy)" for finished episodes. Do you see that display?
![gpod-duration](https://user-images.githubusercontent.com/830975/80209256-63465400-863a-11ea-97eb-8880330939eb.png)
* Now, if you start playing an episode in VLC, and then stop after 10 seconds (IIRC, changes of less than 5 seconds are ignored) -- does the display update accordingly? Or is this the point at which you see it marked as Finished, despite it having only played for 10 seconds?

**Comment by coffee-lord** [comment] 2020-04-24 12:17
> do you see that last played position in the episode listing?

Yes. It shows the duration as you described.

> Now, if you start playing an episode in VLC, and then stop after 10 seconds (IIRC, changes of less than 5 seconds are ignored) -- does the display update accordingly?

It does. It works as expected when I hit "pause". What doesn't work is when I close VLC it marks the episode as "Finished". I.e. I press "pause", so far so good, gPodder updates accordingly, then I quit VLC and as soon as I do that the episode changes to "Finished" even though there's still time remaining.

Dunno, maybe my gentoo setup is acting up again. Usually either something works or it doesn't but in this case it 'almost' works :stuck_out_tongue:

**Comment by auouymous** [comment] 2020-04-24 12:54
From google:
1 Open the VLC Player. Go to Tools > Preferences (or use the Ctrl + P shortcut).
2 On the Interface screen, go down to the choices for Continue playback?
3 Click the dropdown and select Always.

This won't display anything in gpodder, but closing vlc and resuming later should work.

**Comment by coffee-lord** [comment] 2020-04-24 13:05
Yeah, I've already done that, @auouymous. Thanks

The problem is when gPodder syncs it erroneously marks episodes as "Finished" on my phone too, which is very annoying.

**Comment by dovf** [comment] 2020-04-24 13:26
> It does. It works as expected when I hit "pause". What doesn't work is when I close VLC it marks the episode as "Finished". I.e. I press "pause", so far so good, gPodder updates accordingly, then I quit VLC and as soon as I do that the episode changes to "Finished" even though there's still time remaining.

Hmm... FWIW, I don't see that behavior in my setup. So yeah, sounds like a bug *somewhere*...

Probably best to open a separate issue for this? And then if you are able to provide debug output from gpodder (I think starting it with '-v' should do it) while this is happening? (Not that I'm promising I'll have time to look into it, but if not me, someone else maybe...).

**Comment by fabianski7** [comment] 2020-08-25 01:06
for mpv, you can use the option [--save-position-on-quit](https://mpv.io/manual/master/#options-save-position-on-quit)

**Comment by elelay** [comment] 2020-08-25 17:21
The issue should be fixed in 3.10.16.

**Comment by elelay** [comment] 2020-09-12 14:07
Continuing discussion about chapters in #870...

**Closed by elelay** 2020-09-12 14:07 UTC
Labels: needs-info
