### ISSUE TITLE
recalcitrant rss feed

### ISSUE THREAD

**Issue by highflux7** [gpodder/gpodder#600] opened 2019-01-31 05:21 UTC
Not strictly a gPodder issue, more of a request on how to deal with rss feed providers who insist their xml is fine when in fact it is fubar.  In this case, https://www.talkshoe.com/rss-the-bible-geek-show.xml
I have examined the feed with manually with curl and find the PubDate field changes with nearly every poll. Kindly brought this to the attention of the support email account at 'talkshoe' who did reply, but obviously did not understand (and finally admitted) did not comprehend anything technical and said he would bring it up at the next tech meeting.  Weeks have passed and no action has been taken.

Any idea how I can get such issues escalated?  An ever-changing PubDate drives gPodder nuts, keeping old episodes coming back as new time and time again.  I've also written to the author/publisher of the podcast, but he is even more tech illiterate than his feed provider Talkshoe.

Any suggestions would be most welcome!

Thanks for your time.  Know this isn't strictly a gPodder issue/problem, but is an issue not unfamiliar to the ecosystem.

Kind regards.  -hf7

**Comment by elelay** [comment] 2019-01-31 21:51
Maybe you could write an extension to:
1. save old episodes titles for you podcast in on_application_started
2. mark old episodes old again in on_podcast_updated, based on your list from on_application_started
3. add old episodes to the list in on_episode_save for when you mark new episodes old and the update the podcast before quitting/restarting gPodder.
Then you side-step the guid problem using the title as guid.
If there was an extension method to retrieve/process the podcast on update, you could filter it, which would be more elegant...

**Comment by elelay** [comment] 2019-01-31 21:53
Rereading your question, I understand it's not guid but pubdate that change.
My answer still apply : just mark episodes old again (maybe use episodes guid as key instead of title).

**Comment by elelay** [comment] 2019-01-31 21:59
Digging into this more, maybe there is something to fix in gpodder:
there are 2 IPs for www.talkshoe.com so maybe to servers in 2 different timezones.
pubDates are not different, just expressed in different timezones:
```
       <title>The Bible Geek Podcast 16-009</title>
-      <pubDate>Sat, 16 Apr 2016 08:00:00 -0400</pubDate>
+      <pubDate>Sat, 16 Apr 2016 22:00:00 +1000</pubDate>
       <title>The Bible Geek Podcast 16-008</title>
-      <pubDate>Sun, 10 Apr 2016 08:00:00 -0400</pubDate>
+      <pubDate>Sun, 10 Apr 2016 22:00:00 +1000</pubDate>
```

I'll look into it...

**Comment by highflux7** [comment] 2019-02-01 01:31
Thanks!  Very much could be the problem, though the two IP address both route to west coast AWS:

`ec2-54-183-39-210.us-west-1.compute.amazonaws.com` `(54.183.39.210)`
`ec2-13-57-164-134.us-west-1.compute.amazonaws.com` `(13.57.164.134)`

One would think UTC would be the right thing to do in any case.  But heck if I know.

**Comment by elelay** [comment] 2019-02-24 11:25
Closing as I can't reproduce it.

**Closed by elelay** 2019-02-24 11:25 UTC

**Comment by highflux7** [comment] 2019-03-19 00:12
Thanks you for your efforts!  Haven't seen the problem manifest locally in the past month and a half so perhaps whatever was fouling up the works was finally fixed.  (or the *actual* tech folks at "TalkShoe" finally took my complaint under earnest advisement)

Daily TED talks is another feed with similar never ending 'old episodes reappearing as new' problems, but am not worrying about that on as TED, especially daily, is a bit too much enthusiastic positive bs for anyone to swallow.  :-)
