### ISSUE TITLE
Mac version 3.10.1 crashes when exporting an OPML in high sierra

### ISSUE THREAD

**Issue by ghost** [gpodder/gpodder#413] opened 2018-02-24 15:45 UTC
Problem Report for Python3 (Dialog box title) -> Python3 quit unexpectedly (Dialog box text)

**Comment by mckenziec** [comment] 2018-05-16 06:52
This is a huge problem for me. The last gPodder version I used was 3.9.3 and it had no problems on MacOS exporting to a local folder. Now with the latest version I keep running into Python3 unexpected errors with no information. Is there a log or something I can grab and post here?

**Comment by elelay** [comment] 2018-06-10 12:55
I can reproduce it on macOS El Capitan.
This is due to a missing `share/glib-2.0/schemas/org.gtk.Settings.FileChooser.gschema.xml` file

**Comment by mediamode** [comment] 2018-06-11 23:32
I just ran into this problem today.  In addition though, after I deleted  mac version 3.10.1, I attempted to open 3.9.3 (which I kept in a separate folder) and now it will not open at all.

**Comment by samirsushah** [comment] 2018-06-12 04:31
can somebody fix this. i am not a developer. i put on GitHub so that somebody notices the problem.

**Comment by elelay** [comment] 2018-06-14 20:11
Fixed in gPodder 3.10.3.

**Closed by elelay** 2018-06-14 20:11 UTC
Labels: macOS
