### ISSUE TITLE
File extensions removed after renaming episodes with brackets and parentheses

### ISSUE THREAD

**Issue by anewuser** [gpodder/gpodder#1328] opened 2022-07-08 17:50 UTC
Please check if you can reproduce this issue with `Rename episodes after download` on Windows:

![gPodder](https://user-images.githubusercontent.com/6733770/178044018-a2d1d962-ddca-4199-81ec-e1894780d4d7.png)

Podcast URL: https://feeds.soundcloud.com/users/soundcloud:users:12563093/sounds.rss

Edit: this also happened with episodes from other SoundCloud RSS feeds with no special characters in their titles, such as "Patterns 499" from https://feeds.soundcloud.com/users/soundcloud:users:241200/sounds.rss

gPodder 3.10.21
exFAT HD partition
Windows 10

**Comment by auouymous** [comment] 2022-07-09 07:35
This is a soundcloud issue and a duplicate of #1237.

**Closed by auouymous** 2022-07-09 07:35 UTC
Labels: needs-confirmation, windows
