### ISSUE TITLE
'NoneType' object has no attribute 'get_selected'

### ISSUE THREAD

**Issue by IgorFobia** [gpodder/gpodder#165] opened 2016-11-11 14:25 UTC
After selecting some podcast episodes to be downloaded, I got this message:

> Unhandled exception
> 
> Please report this problem and restart gPodder:
> 
> 'NoneType' object has no attribute 'get_selected'

**Comment by vossad01** [comment] 2017-04-12 01:20
@IgorFobia Thanks for reporting this!  I have some follow up questions.

Do you have a specific podcast or episodes this affects or can it otherwise be reproduced?  If not and this happens again, could you provide the full stack trace to so we can better identify the issue?

Also, what version of gPodder are you running?

**Comment by jgmoss** [comment] 2017-06-19 20:32
I'm not the original poster, but I also received this error. I'm using gPodder 3.9.3 on Windows 10.

**Comment by adamvoss** [comment] 2017-06-19 20:49
Thanks for chiming in @jgmoss.  We are still waiting on enough information do be able to do anything towards resolving this issue.  Are you able to answer any of the questions in my previous comment?

**Comment by jgmoss** [comment] 2017-06-19 20:58
It doesn't appear to be related to any specific podcast. I've even tried removing some recently added podcasts to see if the error would stop. I apologize, but I do not know how to provide a full stack trace. Are there instuctions I can follow? If so, I will be happy to provide on.

**Comment by adamvoss** [comment] 2017-06-19 21:07
Can you figure out where your gPodder database lives?  You set a path the first time you run gPodder on windows.  You can try going to the command prompt and running `echo %GPODDER_HOME%` to find it.

In that folder there should be a logs folder.  If you look in the logs you can probably find the log that contains your error.

(The other option is to run gPodder GUI from command line hoping to capture the error on the console, but the log is probably easier)

**Comment by jgmoss** [comment] 2017-06-19 22:07
I found the log folder, but there are no logs there.

**Comment by elelay** [comment] 2019-02-27 18:15
Closing since it's really and might be fixed in the 3.10 branch with the switch to python 3.

**Closed by elelay** 2019-02-27 18:15 UTC
Labels: blocked, bug, needs-info
