### ISSUE TITLE
Escaping ampersand leads to slash in file name

### ISSUE THREAD

**Issue by Strubbl** [gpodder/gpodder#406] opened 2018-02-14 22:59 UTC
gpodder wants to download a file, which has the title "USA & Mexico". But it escapes the ampersand to a slash, which is not good in Linux.

I get the error
`Download error while downloading 24 Tage USA & Mexiko mit Kati: [Errno 2] No such file or directory: '/home/strubbl/gPodder/Downloads/Feed3/USA / Mexico.a.partial'' from markup due to error parsing markup: Error on line 3: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity - escape ampersand as &amp;`

**Comment by elelay** [comment] 2018-02-15 18:37
Sorry about that!
This is a duplicate of #361.
You can either switch gPodder 3.9.6, wait for a new release or run from a git checkout of the master branch.

**Closed by elelay** 2018-02-15 18:37 UTC
Labels: duplicate
