### ISSUE TITLE
Display Issuer on Mac OS

### ISSUE THREAD

**Issue by MrDaleSmith** [gpodder/gpodder#1365] opened 2022-08-11 05:33 UTC
The display for GPodder is broken on MacOS Monterey 12.5: a full screen window shows the interface within a small corner of the screen:

**Comment by auouymous** [comment] 2022-08-11 05:38
Duplicate of #1348.

**Closed by auouymous** 2022-08-11 05:38 UTC

**Comment by JimH44** [comment] 2022-09-06 20:45
Thanks @auouymous for that pointer.
I was able to make the app run in low res mode as suggested there :-)
