### ISSUE TITLE
SSL Timeout

### ISSUE THREAD

**Issue by rjhorn-agfa** [gpodder/gpodder#244] opened 2017-03-23 21:32 UTC
This could be a gpodder or a python issue.  It affects at least the Nature Podcast and Star Ship Sofa.  I debugged this using a Nature podcast.  The network connection is through a privoxy proxy.  I've eliminated the proxy as a primary cause because I do obtain the desired MP3 file using both curl and chrome.

gPodder generates an error after a long timeout:
Failed I/O Error: ('_ssl.c:574: The handshake operation timed out',)

This is with gpodder version 3.9.3.

Privoxy log indicates the start of the chain that then goes into SSL hiding.  It gives an address at feeds.nature.com.  Using curl

`curl feeds.nature.com/~r/nature/podcast/current/~5/r6Vf1-TMT2k/media.mp3`

I get this HTML

```
<HTML>
<HEAD>
<TITLE>Moved Permanently</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>Moved Permanently</H1>
The document has moved <A HREF="https://media.acast.com/nature/naturepodcast-23march2017/media.mp3">here</A>.
</BODY>
</HTML>
```

Then using
`curl https://media.acast.com/nature/naturepodcast-23march2017/media.mp3`

I get
`Found. Redirecting to https://ads-creative-cdn.acast.com/encoded/ed17b105-a78a-43dc-991c-17048777636b/20170322180149-2-128.mp3?ci=087b1b26-9050-48cf-a2bf-7341526d5be9&aid=ed17b105-a78a-43dc-991c-17048777636b&chid=0185cea5-9e3b-4b82-a887-26f91f92765f&st=won8HLH7a2JI7Cwk3Xn7uA&e=1490317430&filename=Nature-Podcast-Nature-Podcast-23-March-2017.mp3`

and using
`curl https://ads-creative-cdn.acast.com/encoded/ed17b105-a78a-43dc-991c-17048777636b/20170322180149-2-128.mp3?ci=087b1b26-9050-48cf-a2bf-7341526d5be9&aid=ed17b105-a78a-43dc-991c-17048777636b&chid=0185cea5-9e3b-4b82-a887-26f91f92765f&st=won8HLH7a2JI7Cwk3Xn7uA&e=1490317430&filename=Nature-Podcast-Nature-Podcast-23-March-2017.mp3`

I get the proper MP3 file.

Using Chrome the https://media.acast.com/nature/naturepodcast-23march2017/media.mp3 URL plays the proper MP3 file.

Since both curl and chrome are successfully retrieving the MP3 file, I think that the problem is in gPodder.

**Comment by vossad01** [comment] 2017-03-27 13:27
What is your Python version?  Can you update it?  I suspect this is the same as #234.

I did not reproduce this when trying to download "Backchat: March 2017" from http://feeds.nature.com/nature/podcast/current

**Comment by rjhorn-agfa** [comment] 2017-03-27 18:40
> 
> What is your Python version? Can you update it? I suspect this is the 
same as 
> #234.
> I did not reproduce this when trying to download "Backchat: March 2017" 
from 
> http://feeds.nature.com/nature/podcast/current


I'm traveling this week.  It should be the current default Python 3 for 
OpenSUSE LEAP 42.2.  I'll check the version when I return, and also try to 
install the most recent release of Python to check whether that fixes it.

R Horn

**Comment by vossad01** [comment] 2017-03-28 02:12
@rjhorn-agfa Sounds good :+1:.  When you do that, make sure you check/update the Python 2 installation because gPodder does not use Python 3.

**Comment by rjhorn-agfa** [comment] 2017-04-05 16:49
> What is your Python version? Can you update it? I suspect this is the 
same as 
> #234.
> I did not reproduce this when trying to download "Backchat: March 2017" 
from 
> http://feeds.nature.com/nature/podcast/current

It's Python 2.7.12, which is the latest in repo for SuSE.  I see that 
2.7.13 is released.  I can try building that Python version if you think 
it will fix it. 

Kind Regards,

Robert Horn | Agfa HealthCare
Interoperability Architect | HE/Technology Office
T  +1 978 897 4860

Agfa HealthCare Corporation, Gotham Parkway 580, Carlstadt, NJ 07072-2405, 
USA
http://www.agfahealthcare.com
http://blog.agfahealthcare.com
Click on link to read important disclaimer: 
http://www.agfahealthcare.com/maildisclaimer

**Comment by vossad01** [comment] 2017-04-05 16:55
I'm running Python 2.7.12 as well, so that is not strictly it.  I can try to reproduce it again.  Does it occur for every episode on that podcast?  Or can you let me know the name of a specific one that has the issue?

**Comment by rjhorn-agfa** [comment] 2017-04-05 19:20
> I'm running Python 2.7.12 as well, so that is not strictly it. I can
> try to reproduce it again. Does it occur for every episode on that 
> podcast? Or can you let me know the name of a specific one that has the 
issue?

It's for every episode of a particular podcast.  I picked that one just 
for debugging and comparison with curl.  I recall an earlier Python issue 
with HTTPS where it made a mistake that affected certain sites only.  It 
was something related to the negotiation and site specific related to 
hostname remapping.  This was fixed quite early in 2.7.  It gave the same 
error message because the TLS negotiation error was not made visible 
anywhere, and eventually the timeout was triggered.

If there is some straightforward way to get visibility into the internals 
of the connection I could try that.  But I don't see a way to turn on that 
level of transaction debugging.  You need to see every TCP level 
transaction to catch the error.  I got that one with wireshark.  I may 
look into whether I can configure a setup so that I can use wireshark 
without having it flooded by all the other network traffic to and from 
this machine.  My suspicion is that these sites are using TLS plus host 
redirects in some slightly different way,  Curl doesn't do the redirects. 
They show up as instructions in the curl result from the first request.

Kind Regards,

Robert Horn | Agfa HealthCare
Interoperability Architect | HE/Technology Office
T  +1 978 897 4860

Agfa HealthCare Corporation, Gotham Parkway 580, Carlstadt, NJ 07072-2405, 
USA
http://www.agfahealthcare.com
http://blog.agfahealthcare.com
Click on link to read important disclaimer: 
http://www.agfahealthcare.com/maildisclaimer 

Adam Voss <notifications@github.com> wrote on 04/05/2017 12:55:02 PM:

**Comment by vossad01** [comment] 2017-04-06 02:51
Does the following work for you in the Python REPL?

``` python
import urllib
fp = urllib.FancyURLopener().open('http://feeds.nature.com/~r/nature/podcast/current/~5/4VJ6eu2S7TI/media.mp3', None)
fp.info()
fp.close()
```

**Comment by rjhorn-agfa** [comment] 2017-04-06 20:32
> Does the following work for you in the Python REPL?
> import urllib
> fp = urllib.FancyURLopener().open('http://feeds.nature.com/~r/
> nature/podcast/current/~5/4VJ6eu2S7TI/media.mp3', None)
> fp.info()
> fp.close()

It fails, but with a lot more information.  Looks like a urllib issue, and 
the new error messages may reveal the cause.

Traceback (most recent call last):
  File "./gpod-test", line 5, in <module>
    fp = 
urllib.FancyURLopener().open('http://feeds.nature.com/~r/nature/podcast/current/~5/4VJ6eu2S7TI/media.mp3', 
None)
  File "/usr/lib64/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib64/python2.7/urllib.py", line 364, in open_http
    return self.http_error(url, fp, errcode, errmsg, headers)
  File "/usr/lib64/python2.7/urllib.py", line 377, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "/usr/lib64/python2.7/urllib.py", line 673, in http_error_301
    return self.http_error_302(url, fp, errcode, errmsg, headers, data)
  File "/usr/lib64/python2.7/urllib.py", line 642, in http_error_302
    headers, data)
  File "/usr/lib64/python2.7/urllib.py", line 669, in redirect_internal
    return self.open(newurl)
  File "/usr/lib64/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib64/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/usr/lib64/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 1278, in connect
    server_hostname=server_hostname)
  File "/usr/lib64/python2.7/ssl.py", line 353, in wrap_socket
    _context=self)
  File "/usr/lib64/python2.7/ssl.py", line 609, in __init__
    self.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 838, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [SSL: UNKNOWN_PROTOCOL] unknown protocol 
(_ssl.c:590)

Kind Regards,

Robert Horn | Agfa HealthCare
Interoperability Architect | HE/Technology Office
T  +1 978 897 4860

Agfa HealthCare Corporation, Gotham Parkway 580, Carlstadt, NJ 07072-2405, 
USA
http://www.agfahealthcare.com
http://blog.agfahealthcare.com
Click on link to read important disclaimer: 
http://www.agfahealthcare.com/maildisclaimer

**Comment by rjhorn-agfa** [comment] 2017-04-06 20:57
Further information.  It appears that urllib2 works properly. I tried this 
based on some comments on other proxy related bugs with urllib.  The 
program:

#!/usr/bin/env python
# -*- coding: utf-8 -*-

import urllib
import urllib2
response = 
urllib2.urlopen('http://feeds.nature.com/~r/nature/podcast/current/~5/4VJ6eu2S7TI/media.mp3')

headers = response.info()
print 'DATE    :', headers['date']
print 'HEADERS :'
print '---------'
print headers

data = response.read()
print 'LENGTH  :', len(data)
print 'DATA    :'
print '---------'
# print data

gives the correct results:

DATE    : Thu, 06 Apr 2017 20:50:41 GMT
HEADERS :
---------
Date: Thu, 06 Apr 2017 20:50:41 GMT

Content-Type: audio/mpeg

Content-Length: 28258293

Connection: close

Content-MD5: GGIPIlsYV42qNmcpYfrd9A==

Last-Modified: Wed, 05 Apr 2017 09:58:38 GMT

ETag: "0x8D47C0A555FB9A6"

x-ms-request-id: fb6f590c-0001-001c-47f8-ae248f000000

x-ms-version: 2013-08-15

x-ms-lease-status: unlocked

x-ms-lease-state: available

x-ms-blob-type: BlockBlob

Access-Control-Expose-Headers: Content-Length,Origin

Access-Control-Allow-Origin: *

Server: NetDNA-cache/2.2

X-Cache: HIT

Accept-Ranges: bytes


LENGTH  : 28258293
DATA    :
---------

(I also ran this printing the data, and it looks like an MP3 although I 
didn't try playing it.)

Kind Regards,

Robert Horn | Agfa HealthCare
Interoperability Architect | HE/Technology Office
T  +1 978 897 4860

Agfa HealthCare Corporation, Gotham Parkway 580, Carlstadt, NJ 07072-2405, 
USA
http://www.agfahealthcare.com
http://blog.agfahealthcare.com
Click on link to read important disclaimer: 
http://www.agfahealthcare.com/maildisclaimer

**Comment by vossad01** [comment] 2017-04-06 21:51
@rjhorn-agfa Thank you for all your detailed reporting!  I cannot reproduce the failure, making me suspect perhaps your proxy is a factor or your `urllib` (or one of its dependencies) may be a different version than mine.  Given this seems to stem from an upstream issue and is not readily reproducible, I am not sure if there is a whole lot of actionable information in this issue.

I would recommend closing this issue and any/all of the following actions:
- Create a new issue requesting gPodder either moves away from `urllib` or makes the choice of library configurable.  Link this issue.
- Pursue the issue with urllib [upstream](https://bugs.python.org/).
    Note: based on the stack trace, this may lead to whatever it uses for SSL support.
- Try the Python 3 branch ([`gtk3`](https://github.com/gpodder/gpodder/tree/gtk3)), in this repository.  Python 3 urllib is not the same as Python 2 urllib, so that may resolve your issue.  You will need to [run gPodder from a Git clone](https://github.com/gpodder/gpodder/wiki/Run-from-Git).

**Comment by rjhorn-agfa** [comment] 2017-04-07 20:39
> I would recommend closing this issue and any/all of the following 
actions:
> Create a new issue requesting gPodder either moves away from urllib 
> or makes the choice of library configurable. Link this issue.

Thanks for the effort.  I'll put in a feature request to switch more of 
gpodder to urllib2.  (Portions of gpodder already use it.)  I'll 
personally try the gtk version.  My first problem with that approach was 
already filed as  a bug and a workaround described. 

Kind Regards,

Robert Horn | Agfa HealthCare
Interoperability Architect | HE/Technology Office
T  +1 978 897 4860

Agfa HealthCare Corporation, Gotham Parkway 580, Carlstadt, NJ 07072-2405, 
USA
http://www.agfahealthcare.com
http://blog.agfahealthcare.com
Click on link to read important disclaimer: 
http://www.agfahealthcare.com/maildisclaimer

**Comment by vossad01** [comment] 2017-04-12 02:09
Sounds good :+1:

**Closed by vossad01** 2017-04-12 02:09 UTC
