### ISSUE TITLE
Broken gPodder 3.10.18 macOS app: ModuleNotFoundError: No module named 'urllib3'

### ISSUE THREAD

**Issue by chazzofalf** [gpodder/gpodder#1008] opened 2021-04-12 15:48 UTC
gPodder for mac fails to launch on Mac OS Big Sur with error No module named 'urllib3'

Error Text/Stacktrace below
bash-3.2$ /Applications/gPodder.app/Contents/MacOS/gpodder                      
str=/Applications/gPodder.app/Contents/Resources
filename=                                                              [126/510]
Could not find platform independent libraries <prefix>                          
Could not find platform dependent libraries <exec_prefix>                       Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]                        
ARGV[0]=/Applications/gPodder.app/Contents/MacOS/gpodder                        
System Path:                                                                     /Applications/gPodder.app/Contents/Resources/lib/python36.zip                  
/Applications/gPodder.app/Contents/Resources/lib/python3.8                      
/Applications/gPodder.app/Contents/Resources/lib/python3.8/plat-darwin          /Applications/gPodder.app/Contents/Resources/lib/python3.8/lib-dynload          
/Applications/gPodder.app/Contents/Resources/lib/python3.8/site-packages        
/Applications/gPodder.app/Contents/Resources                                    TERM_PROGRAM=Apple_Terminal                                                     
TERM=screen-256color                                                            
SHELL=/bin/bash                                                                 TMPDIR=/var/folders/00/6tnjw__53xs81f_bxgfdxtp1fpfd1v/T/                        
TERM_PROGRAM_VERSION=440                                                        
BYOBU_CONFIG_DIR=/Users/**redacted**/.byobu                                TERM_SESSION_ID=927E4BFD-387B-497E-8561-F7C1E6B5171F                            
BYOBU_TTY=/dev/ttys000                                                          
BYOBU_READLINK=greadlink
USER=**redacted**                                                 [105/510]
BYOBU_RUN_DIR=/Users/**redacted**/.cache/byobu                             
BYOBU_DISTRO=macOS                                                              SSH_AUTH_SOCK=/Users/**redacted**/.byobu/.ssh-agent                        
BYOBU_DATE=%Y-%m-%d                                                             
TMUX=/private/tmp/tmux-1567044667/default,1472,1                                BYOBU_SED=gsed                                                                  
BYOBU_BACKEND=tmux                                                              
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/go/bin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Apple/usr/
bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/X
amarin Workbooks.app/Contents/SharedSupport/path-bin:/Users/charlesmontgomery/Library/Python/3.9/bin:/Users/**redacted**/bin                               
__CFBundleIdentifier=com.apple.Terminal                                         
BYOBU_DARK=\#333333                                                             PWD=/Users/**redacted**                                            
BYOBU_ULIMIT=ulimit                                                             
LANG=en_US.UTF-8                                                                XPC_FLAGS=0x0                                                                   
TMUX_PANE=%1                                                                    
BYOBU_EDITOR=
BYOBU_WINDOW_NAME=-                                                     [84/510]
BYOBU_CHARMAP=UTF-8                                                             
XPC_SERVICE_NAME=0                                                              SHLVL=3                                                                         
HOME=/Users/**redacted**                                                   
BYOBU_LIGHT=\#EEEEEE                                                            BYOBU_TERM=screen-256color                                                      
LOGNAME=**redacted**                                                       
BYOBU_PAGER=less                                                                BYOBU_ACCENT=\#75507B                                                           
BYOBU_PREFIX=/usr/local/Cellar/byobu/5.133                                      
DISPLAY=/private/tmp/com.apple.launchd.qFJ5WiezQO/org.xquartz:0                 BYOBU_HIGHLIGHT=\#DD4814                                                        
BYOBU_TIME=%H:%M:%S                                                             
_=/Applications/gPodder.app/Contents/MacOS/gpodder                              __CF_USER_TEXT_ENCODING=0x5D67343B:0x0:0x0
PYTHONOPTIMIZE=yes                                                              
CHARSETALIASDIR=/Applications/gPodder.app/Contents/Resources/lib                DYLD_LIBRARY_PATH=/Applications/gPodder.app/Contents/Resources/lib              
GTK_DATA_PREFIX=/Applications/gPodder.app/Contents/Resources                    
GTK_EXE_PREFIX=/Applications/gPodder.app/Contents/Resources
GTK_PATH=/Applications/gPodder.app/Contents/Resources                   [63/510]
LD_LIBRARY_PATH=/Applications/gPodder.app/Contents/Resources/lib                
XDG_CONFIG_DIRS=/Applications/gPodder.app/Contents/Resources/etc                XDG_DATA_DIRS=/Applications/gPodder.app/Contents/Resources/share                
PANGO_LIBDIR=/Applications/gPodder.app/Contents/Resources/lib                   
PANGO_RC_FILE=/Applications/gPodder.app/Contents/Resources/etc/pango/pangorc    PANGO_SYSCONFDIR=/Applications/gPodder.app/Contents/Resources/etc               
GDK_PIXBUF_MODULE_FILE=/Applications/gPodder.app/Contents/Resources/lib/gdk-pixb
uf-2.0/2.10.0/loaders.cache                                                     GTK_IM_MODULE_FILE=/Applications/gPodder.app/Contents/Resources/etc/gtk-3.0/gtk.
immodules                                                                       
GI_TYPELIB_PATH=/Applications/gPodder.app/Contents/Resources/lib/girepository-1.0                                                                               
PYTHONHOME=/Applications/gPodder.app/Contents/Resources                         
No regenerating /Users/charlesmontgomery/Library/Application Support/gPodder/openssl/cert.extracted.pem it's fresh enough
1618241845.669612 [gpodder.log] ERROR: Uncaught exception: Traceback (most recen
t call last):                                                                     File "", line 174, in <module>                                                
  File "/Applications/gPodder.app/Contents/Resources/lib/python3.8/runpy.py", li
ne 265, in run_path
    return _run_module_code(code, init_globals, run_name,               [42/510]
  File "/Applications/gPodder.app/Contents/Resources/lib/python3.8/runpy.py", li
ne 97, in _run_module_code                                                          _run_code(code, mod_globals, init_globals,                                  
  File "/Applications/gPodder.app/Contents/Resources/lib/python3.8/runpy.py", li
ne 87, in _run_code                                                                 exec(code, run_globals)                                                     
  File "/Applications/gPodder.app/Contents/Resources/bin/gpodder", line 166, in 
<module>                                                                            main()                              
  File "/Applications/gPodder.app/Contents/Resources/bin/gpodder", line 158, in 
main                                                                                from gpodder.gtkui import app                                               
  File "/Applications/gPodder.app/Contents/Resources/lib/python3.8/site-packages
/gpodder/gtkui/app.py", line 31, in <module>                                        from gpodder import core, util     
  File "/Applications/gPodder.app/Contents/Resources/lib/python3.8/site-packages
/gpodder/core.py", line 25, in <module>                                             from gpodder import config, dbsqlite, extensions, model, util               
  File "/Applications/gPodder.app/Contents/Resources/lib/python3.8/site-packages
/gpodder/config.py", line 34, in <module>  
    from gpodder import jsonconfig, util                                [21/510]
  File "/Applications/gPodder.app/Contents/Resources/lib/python3.8/site-packages
/gpodder/util.py", line 64, in <module>                                             import requests
  File "/Applications/gPodder.app/Contents/Resources/lib/python3.8/site-packages
/requests/__init__.py", line 43, in <module>                                        import urllib3                                                              
ModuleNotFoundError: No module named 'urllib3'
                                                                                Traceback (most recent call last):     
  File "", line 174, in <module>                                                
  File "/Applications/gPodder.app/Contents/Resources/lib/python3.8/runpy.py", line 265, in run_path                                                             
    return _run_module_code(code, init_globals, run_name,
  File "/Applications/gPodder.app/Contents/Resources/lib/python3.8/runpy.py", line 97, in _run_module_code             
    _run_code(code, mod_globals, init_globals,
  File "/Applications/gPodder.app/Contents/Resources/lib/python3.8/runpy.py", line 87, in _run_code                                                             
    exec(code, run_globals)
  File "/Applications/gPodder.app/Contents/Resources/bin/gpodder", line 166, in
<module>
    main()
  File "/Applications/gPodder.app/Contents/Resources/bin/gpodder", line 158, in main
    from gpodder.gtkui import app
  File "/Applications/gPodder.app/Contents/Resources/lib/python3.8/site-packages/gpodder/gtkui/app.py", line 31, in <module>
    from gpodder import core, util
  File "/Applications/gPodder.app/Contents/Resources/lib/python3.8/site-packages/gpodder/core.py", line 25, in <module>
    from gpodder import config, dbsqlite, extensions, model, util
  File "/Applications/gPodder.app/Contents/Resources/lib/python3.8/site-packages/gpodder/config.py", line 34, in <module>
    from gpodder import jsonconfig, util
  File "/Applications/gPodder.app/Contents/Resources/lib/python3.8/site-packages/gpodder/util.py", line 64, in <module>
    import requests
  File "/Applications/gPodder.app/Contents/Resources/lib/python3.8/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'
Run Simple File returned -1

**Comment by elelay** [comment] 2021-04-12 19:15
Confirmed: I didn't see it because it was a new dependency.

**Comment by elelay** [comment] 2021-04-14 19:57
This will be fixed in next release in a few days.

**Comment by elelay** [comment] 2021-04-15 19:54
Fixed in 3.10.19

**Closed by elelay** 2021-04-15 19:54 UTC
Labels: macOS
