### ISSUE TITLE
Show which feed is being updated

### ISSUE THREAD

**Issue by Vrihub** [gpodder/gpodder#329] opened 2017-07-13 19:30 UTC
While gpodder is checking feeds for new updates, there is no way for the user to know which feed is being checked, neither in the UI (I'm using  the GTK client on Linux), nor in the log file.

This would be very useful to debug the following scenario: one of the feeds has some kind of problem and blocks all other feed updates, until a certain timeout period elapses. I'd like to know which feed is causing the problem. Currently all I can see in the log file is the message 

` [gpodder.gtkui.main] ERROR: Error: timed out`

but there is no way to know which feed is timing out (of course I could check for current TCP connections, but it's not always useful: I only get the IP address of the remote server, which can handle multiple feeds).

Please add the name of the feed being checked to the log messages.
(also adding it somewhere in the UI would be even better)

**Comment by adamvoss** [comment] 2017-07-13 20:29
@Vrihub is this a duplicate of #275?

**Comment by Vrihub** [comment] 2017-07-14 13:23
> @Vrihub is this a duplicate of #275?

Ah, thanks. Sorry I couldn't find it. That's good for the UI.
Anyway, I would still suggest you to add the name of the currently updating feed to the log output; it could be useful in other debugging situations.

**Comment by adamvoss** [comment] 2017-07-14 22:18
@Vrihub What is this magic is this?  How did you tell GitHub to mark it at as a duplicate?

Regarding the logging:  Are you saying to always log the currently updating feed, or are you saying to add it when an error is thrown like in your first example?  If it is the latter, that should be a simple change (identify where the error is thrown from the stack trace, then add the needed message). Would you be interested in trying your hand at a PR for this?

**Comment by Vrihub** [comment] 2017-07-15 11:43
> @Vrihub What is this magic is this? How did you tell GitHub to mark it at as a duplicate?

I really don't know. I guess that my quoting of your line containing the "duplicate" word and the ticket number did the trick. github bug/feature?

> Regarding the logging: Are you saying to always log the currently updating feed, or are you saying to add it 
when an error is thrown like in your first example?  If it is the latter, that should be a simple change

I don't know the code base, but I would guess the former is simpler (doesn't need to check for the error condition). BTW the stack trace is already contained in the log, but it doesn't mention the feed name/url.

**Closed** 2018-08-15 13:57 UTC
Labels: enhancement
