### ISSUE TITLE
Gpodder Downloading All youtube Episodes Every Time

### ISSUE THREAD

**Issue by ChrisMTheMan** [gpodder/gpodder#888] opened 2020-10-22 18:10 UTC
About a week ago Gpodder suddenly began trying to download every episode of every subscription every time a download cycle starts.  I am using Gpodder 3.10.16.  I have not recently updated Gpodder nor done any Windows updates.

**Comment by elelay** [comment] 2020-10-22 18:55
Hi,
thanks for reporting.
Have you checked that *Preferences > Updating > When new episodes are found* is not set to *Download Immediately* if it's not what you want?

**Comment by ChrisMTheMan** [comment] 2020-10-22 18:57
I do want them to download immediately.  The problem is, instead of just downloading new episodes, it's redownloading entire podcasts.  And not just a select few podcasts, it's trying to redownload all of my subscribed podcasts.

**Comment by elelay** [comment] 2020-10-22 19:07
Strange... This can happen if the podcast provider resets the episode ids, forcing gPodder to consider them as new even if the content is the same. Does it really happen for all your podcasts?
Can you try running gPodder in debug mode, to gather more info about the issue ?
See [this link](https://gpodder.github.io/docs/windows.html#debugging-gpodder-on-windows).

**Comment by ChrisMTheMan** [comment] 2020-10-22 19:10
It does happen on nearly all of them.  It's done it several times now, redownloading entire podcasts over and over.  I'll try debug mode and see what we get.

**Comment by ChrisMTheMan** [comment] 2020-10-22 20:27
Rebooted computer, started Gpodder in debug mode and got errors as seen in ss1.jpg attachment.  Closed Gpodder and reopened normally.  It's cataloging all episodes for all podcasts and looks like it will try and download them.  It's not only going very slow but some of the podcast descriptions are showing up in arabic as seen in ss2.jpg.  Updated virus definitions (Avast) and scanned compuer, nothing found.  Should I just reinstall Gpodder?
![ss1](https://user-images.githubusercontent.com/64171309/96926311-44e6d700-146a-11eb-8da0-04155569c285.jpg)
![ss2](https://user-images.githubusercontent.com/64171309/96926323-47493100-146a-11eb-9196-7f4e48094844.jpg)

**Comment by auouymous** [comment] 2020-10-22 20:28
Open podcast settings for one with an error and paste error here. It is probably a corrupt database file.

**Comment by ChrisMTheMan** [comment] 2020-10-22 20:34
The error messages from the first go around aren't happening at this point.  That happened when I had Gpodder started in debug mode.  Restarting Gpodder without the debug option generated what is being seen in the second screenshot.  I concur about the database error.  I've been a DBA for 30 years and have seen this type of wonkiness before.  How does one go about detecting and fixing corruption in this database?

**Comment by auouymous** [comment] 2020-10-22 20:45
A backup is the best way to recover.

This will tell you if the database is corrupt.
```
echo -e "pragma integrity_check;\n.quit" |sqlite3 Database
```

**Comment by ChrisMTheMan** [comment] 2020-10-22 20:56
I don't have sqlite3 available at the command line.  I used DB Browser for sqlite.  The integrity check ran fine.
![ScreenHunter_397 2020-10-22 13 54](https://user-images.githubusercontent.com/64171309/96929057-61850e00-146e-11eb-826f-9092280a733d.jpg)

**Comment by auouymous** [comment] 2020-10-22 21:00
Did gpodder not produce a log file when you ran it in debug mode? If not, try again and hover over the channel icons to read error message.

**Comment by ChrisMTheMan** [comment] 2020-10-22 22:52
It displayed the first screen I posted and then hung.  None of the channels display any errors at this point.  I looked through the database and noticed over 2500 records with the is_new flag set to 1.  Is that normal?  Is there a schema document I can take a look at?

**Comment by auouymous** [comment] 2020-10-23 00:50
It should have generated a partial debug log file before it hung.

**Comment by ChrisMTheMan** [comment] 2020-10-23 00:52
I'll start it again in debug mode if it happens again.  Oddly, at this point, it seems to have stopped.

**Comment by auouymous** [comment] 2020-10-23 01:09
There should be a file in the logs directory from the previous debug start.

If this happened to me and I didn't have backups, I would export to OPML, remove the database file and import the OPML to guarantee a clean database. At a minimum, export to OPML in case the database completely dies soon.

**Comment by ChrisMTheMan** [comment] 2020-10-23 02:47
I have an export of the OPML.  If I import it into a clean database isn't it going to redownload every episode of all my podcasts?  That's the problem I am having now.

**Comment by auouymous** [comment] 2020-10-23 03:00
You can turn off auto-download, import OPML, delete old episodes, and then turn auto-download back on.

**Comment by ChrisMTheMan** [comment] 2020-10-23 18:24
I just completed this task.  It was painful with 80+ podcasts.  We'll see if it starts the mass downloads again.  Thank you for the guidance so far...

**Comment by ChrisMTheMan** [comment] 2020-10-24 15:39
It started the downloading all over again.  Blew up my hard drive with 300+ gigs of downloads overnight.  Should I reinstall Gpodder?

**Comment by phobeus81** [comment] 2020-10-25 21:53
I can confirm this observation as well. Since a few days, GPodder is downloading everything it can gather. I first also thought that single channels would have reorganized something, but its now starting to download new episodes again that I just marked as seen a few days.

**Comment by ChrisMTheMan** [comment] 2020-10-25 22:51
I am using the youtube-dl extension too.  Not sure if that factors in.

**Comment by ChrisMTheMan** [comment] 2020-10-28 17:31
I unchecked the youtube-dl option and it seems to be downloading normally.  Phobeus81, you may want to check this to see how you are set up and if it makes a difference for you.  Dev's, is it possible in light of the DMCA challenge on youtube-dl that Youtube is somehow detecting that the software is being used and is causing problems on purpose?

**Comment by phobeus81** [comment] 2020-10-28 20:15
Yes, I am also using youtube-dl and now deactivated the extension and not observed a mass download within the last days. So I blame the extension ATM.

**Comment by ChrisMTheMan** [comment] 2020-10-31 19:12
I've had the youtube-dl extension unchecked for several days now.  All the crazy downloading activity is gone.  The extension seems to be the problem.  It's up to the devs now.

**Comment by Gestas** [comment] 2020-11-02 19:24
It may be a coincidence, the timing of this issue is well correlated with youtube-dl being removed from Github. 

https://github.com/ytdl-org/youtube-dl
https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA.md

**Comment by elelay** [comment] 2020-11-03 17:45
There is also a new youtube-dl release 2020.11.1.1 on [pypi](https://pypi.org/project/youtube_dl/) that fixes player url parsing.
If any brave soul wants to try it, they have to copy it in place of the youtube_dl folder in the gpodder install directory...

**Comment by ChrisMTheMan** [comment] 2020-11-10 19:18
I've tested this new version as a standalone and it works great so I have copied it into the youtube-dl folder and have re-enabled the extension as well as marked new episodes as "Do Nothing".

Brave or foolish...take your pick.  :)

**Comment by ChrisMTheMan** [comment] 2020-11-10 20:48
Well, it partially worked.  It did properly download some episodes but I also have renaming turned on and it failed during that.

**Comment by ChrisMTheMan** [comment] 2020-11-13 05:42
Has this problem been abandoned?  Without the youtube-dl extension Gpodder does not download the highest resolution video available.

**Comment by auouymous** [comment] 2020-11-13 07:59
Everyone is busy, but I'll try to take a look tomorrow.

The extension has two options: manage_channels and manage_downloads. You should still be able to use manage_downloads to always download non-standard formats with youtube-dl. The manage_channel setting uses youtube-dl to fetch the episode list, and allows for more than the 15-20 limit that gpodder's method has. It is most likely manage_channels that is causing the problem.

**Comment by auouymous** [comment] 2020-11-14 11:21
That patch should fix the issue by aborting when youtube-dl returns an empty episode list for a channel. Without the patch, the extension removes all episodes, and a future update adds them all back as new. The problem doesn't happen with all youtube channels because the extension only manages channels that have 'channel' in the URL, those with 'user=' are handled by gpodder.

**Comment by auouymous** [comment] 2020-11-15 22:17
youtube-dl-2020.11.12 appears to have fixed the issue, can anyone confirm or deny?

**Comment by ChrisMTheMan** [comment] 2020-11-15 22:58
I tried it a few days back and reported it here.  Downloading worked fine but file renaming failed.  Upon trying to rename, Gpodder left the original file with it's original name and a zero byte file with the proper name.

**Comment by ChrisMTheMan** [comment] 2020-11-15 23:09
FWIW, I did put the new youtube-dl in this folder:  C:\Users\username\Documents\gPodder\youtube-dl

**Comment by auouymous** [comment] 2020-11-15 23:24
2020.11.12 wasn't available 5 days ago when you reported. This issue is about the `manage_channels` setting causing episodes to be marked as new after being deleted. Problems with downloads not being renamed need to be handled separately.

**Comment by ChrisMTheMan** [comment] 2020-11-15 23:25
Indeed, I have 2020.11.01.1.  I'll try this new version.

**Comment by ChrisMTheMan** [comment] 2020-11-16 01:06
After installing the newest version of youtube-dl to C:\Users\username\Documents\gPodder\youtube-dl, upon trying to download 3 new episode, all gave errors.

1 error for "requested format not available"
1 error for "unable to extract JS player URL
1 error for "youtube said unable to extract video data"

Disabling the use of youtube-dl and retrying the downloads was successful.  Am I putting youtube-dl.exe in the right folder?  This is a Windows machine.

**Closed** 2020-11-21 14:43 UTC

**Comment by ChrisMTheMan** [comment] 2020-11-21 16:25
Thank you for your work on this everyone!
